default_stages: [commit, push]
exclude: ^src/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: end-of-file-fixer
        types: [python]

    -   id: check-json
        types: [json]

    -   id: check-yaml
        types: [yaml]

    -   id: trailing-whitespace
        types: [python]

    -   id: flake8
        types: [python]
        args: [--ignore=E501]

    -   id: check-merge-conflict


-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.2.2
    hooks:
    -   id: pylint
        types: [python]
