default_stages: [commit, push]
exclude: ^src/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=10000]

    -   id: check-json

    -   id: check-merge-conflict

    -   id: check-yaml

    -   id: end-of-file-fixer
        types: [python]

    -   id: fix-encoding-pragma
        args: [--remove]

    -   id: file-contents-sorter
        files: src/unpacker/passwords|.gitignore|_list.txt

    -   id: flake8

    -   id: forbid-new-submodules

    -   id: no-commit-to-branch

    -   id: pretty-format-json
        args: [--autofix]

    -   id: trailing-whitespace
        types: [python]
        args: [--ignore=E501]


-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.2.2
    hooks:
    -   id: pylint
        types: [python]
        args: [--rcfile=.pylintrc]
