name: Deploy Docs to github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    # check out repository
    - uses: actions/checkout@v2

    # install deps and trigger docs build
    - name: Build Docs
      run: |
        pip3 install --user -r docsrc/doc_dependencies.txt
        make -C docsrc html

    # deploy built docs
    - name: Deploy Docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docsrc/_build/html
